version: '3.6'

services:

 mongo:
   container_name: docker_mongo
   #environment:
   #   MONGO_INITDB_ROOT_USERNAME: nome_do_usuario_do_mongo
   #   MONGO_INITDB_ROOT_PASSWORD: senha_do_usuario_do_mongo
   image: mongo:latest
   #volumes:
   #  - D:\Cursos\star-wars-api\db:/data/db

 spring:
   container_name: docker-spring
   ports:
     - "8080:8080"
   environment:
     - JAVA_TOOL_OPTIONS=-Djava.security.egd=file:/dev/./urandom -Duser.timezone=America/Sao_Paulo  -Dspring.data.mongodb.uri=mongodb://docker_mongo:27017/starwars
     - TZ=America/Sao_Paulo
   depends_on:
     - mongo
   image: star-wars